### ISSUE TITLE
Additional Space Beneath Tags on Android

### ISSUE THREAD

**Issue by AtlasAF01** [daniel-luberda/DLToolkit.Forms.Controls#60]
The control renders additional space beneath the tags on Android.  Is there a way to control this?

![image](https://cloud.githubusercontent.com/assets/25185688/22040037/2165b24e-dcc7-11e6-8ffb-46559acbaa26.png)

**Comment by AtlasAF01** [comment]
Identified the problem and providing it here until the fix can be incorporated into the master branch.  There is two parts; first, in our usage, we hide the input field and binding to a list of values selected on a different page.  Second, we used labels inside of frames with a set height of 28.  

Regardless if the TagEntry fields visibility, it was always appended as the last child during the ForceReload method.  The LayoutChildren method correctly ignore the entry field during layout however, the entry field was still used by the DoHorizontalMeasure.  Since the entry field was larger than our tags, the entry field height was used to determine the overall height for the control.

In the ForceReload() method, I changed:

`Children.Add(TagEntry);` 

to

`if (TagEntry.IsVisible) Children.Add(TagEntry);`

which fixed the extra space issue for us.

**Comment by daniel-luberda** [comment]
@AtlasAF01 Great! Thanks for a PR. I'll merge it now. 👍

**Comment by nd-srogers** [comment]
I'm getting this same problem, however I have @AtlasAF01 's fix in my `TagEntryView`.

For me it seems like the more tags I have, the larger the space below the TagEntry gets. I've looked through the code in `TagEntryView` and can't see anything particularly untoward that might cause this.

![image](https://user-images.githubusercontent.com/33408863/37953680-f0b49ce8-31e6-11e8-9f9d-142177669fc3.png)

In that image there are about 50 total tags. Note the line for the Tag Entry is in the correct place. It seems to be the container's height that is incorrectly set. Some of the tags are quite long and would spread over two lines, however I am using `LineBreakMode="TailTruncation"` so that every tag is only on one line.
